name: calculadora-api-python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fem checkout del repositori
      uses: actions/checkout@v4

    - name: Instalacio de python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalacio de Flask y curl
      run: |
        sudo apt-get install -y curl
        pip install flask

    - name: Obrim la pagina
      run: |
        python3 api_calculadora &
        sleep 5

    - name: Tests
      run: |
        curl -s http://localhost:5000/suma/7/10 | grep "17" 
        curl -s http://localhost:5000/resta/10/7 | grep  "3" 
        curl -s http://localhost:5000/multiplica/2/10 | grep  "20" 
        curl -s http://localhost:5000/divisio/10/2 | grep  "5" 
